FUNC ID OPEN_PAREN CLOSE_PAREN ARROW TYPE OPEN_BRACE 
TYPE ASSIGN DLITERAL SEMI 
TYPE ID OPEN_BRACKET CLOSE_BRACKET ASSIGN SLITERAL SEMI 
IF OPEN_PAREN ID TEST_EQ DLITERAL CLOSE_PAREN OPEN_BRACE 
ID ASSIGN DLITERAL SEMI 
CLOSE_BRACE 
ID OPEN_BRACE 
ID ASSIGN DLITERAL SEMI 
CLOSE_BRACE 
WHILE OPEN_PAREN ID GREATERTHAN DLITERAL CLOSE_PAREN OPEN_BRACE 
ID MINUS MINUS SEMI 
CLOSE_BRACE 
ID PLUS PLUS SEMI 
CLOSE_BRACE 

FUNC OPEN_PAREN TYPE ID COMMA TYPE ID CLOSE_PAREN ARROW TYPE 
TYPE ID ASSIGN ID PLUS ID SEMI 
RET ID SEMI 
CLOSE_BRACE 
